#!/usr/bin/env bash

### 
# Fuctions
###

function _help() {
  echo "
  Usage:
    setup_server [arguments]

  Commands:
    help     Print Help/Usage Text
    upgrade  Upgrade an existing installation
    install  Install everything and all dependencies
    "
}

function _install() {
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  sudo "$DIR"/vagrant-provision.sh
  "$DIR"/install-sources.sh
  "$DIR"/user-provision.sh
}

function _upgrade() {
  _install
}


###
# Main Script
###
case "$1" in 
  upgrade)
    _upgrade
    ;;

  install)
    _install
    ;;

  *)
    _help
    ;;
esac

exit 0

